import type { Metadata } from 'next'
import { Space_Grotesk } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

const space_grotesk = Space_Grotesk({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-space-grotesk',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${space_grotesk.variable} scroll-smooth dark`}>
      <body>
        <div className="flex min-h-screen flex-col justify-between">
          <Header></Header>
          <main className="mt-10 p-10 mb-auto">{children}</main>
        </div>
        <Footer></Footer>
      </body>
    </html>
  )
}
