components:
  schemas:
    ResponseProfileSchema:
      type: object
      required: [language]
      xml:
        name: ResponseProfileSchema
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        email:
          type: string
          format: email
        tel:
          type: string
        post:
          type: string
        address:
          type: string
        createdAt:
          type: string
          example: "2023/12/13 8:39:04"
        updatedAt:
          type: string
          example: "2023/12/13 8:39:04"
    ProfileSchema:
      type: object
      xml:
        name: ProfileSchema
      properties:
        success:
          type: boolean
          example: true
        data:
          type: array
          items:
            $ref: '#/components/schemas/ResponseProfileSchema'