components:
  schemas:
    HealthSchema:
      type: object
      xml:
        name: HealthSchema
      properties:
        success:
          type: boolean
          example: true
        data:
          type: string
          example: OK