components:
  schemas:
    LanguageCookieSchema:
      type: object
      xml:
        name: LanguageCookieSchema
      properties:
        language:
          type: string
          example: en
    ThemeCookieSchema:
      type: object
      xml:
        name: ThemeCookieSchema
      properties:
        theme:
          type: string
          example: dark