components:
  schemas:
    ErrorSchema:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int64
        message:
          type: string
          example: error
        path:
          type: string
        timestamp:
          type: string
          format: date-time
      xml:
        name: errorSchema