components:
  schemas:
    ErrorSchema:
      type: object
      required:
        - code
        - message
      properties:
        success:
          type: boolean
          example: false
        error:
          type: object
          properties:
            code:
              type: integer
              format: int64
            message:
              type: string
              example: error
            path:
              type: string
            timestamp:
              type: string
              format: date-time
      xml:
        name: errorSchema