/**
 * Landing Page API
 * This is Landing Page API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * database model
 */
export interface Profile { 
    id?: string;
    name?: string;
    email?: string;
    tel?: string;
    post?: string;
    address?: string;
    language: string;
    isActive?: boolean;
    createdAt?: Date;
    updatedAt?: Date;
}