name: Landing Page Frontend Image

run-name: ${{ github.actor }} is learning GitHub Actions

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy job
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./01-LandingPage/Dockerfile/Production/Frontend.Dockerfile
          push: true
          tags: cdq73700/landing-page-frontend:latest